### ISSUE TITLE
Extension: Create new seahorse project creates anchor project

### ISSUE THREAD

**Issue by denimcodes** [solana-playground/solana-playground#102]
When I create a new seahorse project in vscode with solana playground extension, it creates a new anchor project instead of seahorse. 

<img width="966" alt="Screenshot_20230103_142540" src="https://user-images.githubusercontent.com/95026200/210326090-197cb773-bd3b-4c23-a819-e7eda4d232b5.png">
<img width="966" alt="Screenshot_20230103_142707" src="https://user-images.githubusercontent.com/95026200/210326124-118e4dd6-83bb-49ef-87dc-606c6bb9f000.png">

**Comment by acheroncrypto** [comment]
Anchor project gets initialized first when creating a Seahorse project. Seahorse files should be created after the dependency installation for Anchor. If not, could you provide the steps you've taken so I can reproduce it?

**Comment by denimcodes** [comment]
I am sharing a screen record of me creating a new seahorse project on vscode.


https://user-images.githubusercontent.com/95026200/210442475-e309308d-7c3b-47dd-beef-25ac14614772.mp4

**Comment by acheroncrypto** [comment]
Thanks, I think the issue here is that you close the old vscode process when the Seahorse creation is still ongoing. As I've mentioned in the previous post, it creates the Seahorse files after Anchor installation completes but since you are starting a new vscode process with `code -r .`, Seahorse creation doesn't get to the next step, which is the creation of Seahorse files.

Let me know if this is still an issue if you don't close the initial vscode window until Seahorse files are created.

**Comment by denimcodes** [comment]
This time I waited for installation to complete and it's working as expected. Thanks.
