### ISSUE TITLE
Bug: Program Id isn't updated on build if not in lib.rs

### ISSUE THREAD

**Issue by mcintyre94** [solana-playground/solana-playground#105]
Repro: 

- Import (with github import): https://github.com/clockwork-xyz/examples/tree/main/hello_clockwork/programs/hello_clockwork

This project has an `id.rs` file containing:

```rs
use anchor_lang::prelude::declare_id;

declare_id!("7ewJenSx5sX6DagEhBDvD76sUb5RUck7zZZ6iAqFBZyE");
```

- Build the workspace

- The ID isn't updated, and if you deploy and call an instruction you'll get the mismatched program ID error

Pretty sure it's caused by this:
https://github.com/solana-playground/solana-playground/blob/master/client/src/utils/pg/explorer/explorer.ts#L1047-L1048

Maybe we can just change this to `endWith(".rs")` like we do with `.py`?

**Comment by acheroncrypto** [comment]
> Maybe we can just change this to endWith(".rs") like we do with .py?

I think we can do this but there is a small difference: It's fine for Python files since Playground only supports single-file Seahorse projects but for Rust, we should stop the Regex check after the program id file has been found. The priority and starting point should be `lib.rs` since its convention for most programs.
