### ISSUE TITLE
Syntax for JSONRPC Call to depoloyed contract

### ISSUE THREAD

**Issue by davidlampach** [solana-playground/solana-playground#112]
I am trying to avoid using the JS web3 solana library.  But using that library I am able to access functions and variables in an already deployed contract on my localnet.  As I understand it, the web3 library sits on top of the JSONRPC library, and therefore I should be able to structure transactions without web3, and also using this wasm client.

Are there any good code examples of a simple request to a function to get data, or perhaps execute the function?

**Comment by acheroncrypto** [comment]
You can check out any repo that uses `solana-client` because `solana-client-wasm` crate methods are basically the same.

You only need to create `solana_sdk::transaction::Transaction` to send a transaction. You can check [spl-token-cli-wasm](https://github.com/solana-playground/solana-playground/tree/bf60102245adb85a4c2d2e715b81b81d669db5d8/wasm/spl-token-cli) crate in this repository, for example [mint-command](https://github.com/solana-playground/solana-playground/blob/bf60102245adb85a4c2d2e715b81b81d669db5d8/wasm/spl-token-cli/src/cli.rs#L1232).

**Comment by davidlampach** [comment]
Thanks for the info.  I checked out your Solana Playground.  Very cool.  Seems like there is a ton of potential to make that into an essential tool.  I like that you are modelling it on Remix.

**Comment by davidlampach** [comment]
I did get this figured out.  

The following repo is very helpful since it implements a pure rust client.  You have to work through and switch it over to solana-client-wasm, but all the basic functionality is there.  After some tinkering, I was able to get data from contract storage and deserialize the output as readable information.  For that, one only needs get_account() and a wasmclient connection.  If you want to call a function, you have to structure a transaction, since that call requires an authorized signer.  Either way, the simple-solana-program repo is dead on for people looking to accomplish this in pure rust.

https://github.com/0xekez/simple-solana-program
