### ISSUE TITLE
"This transaction has already been processed." error when sending transactions in close succession

### ISSUE THREAD

**Issue by mcintyre94** [solana-playground/solana-playground#116]
If you send the same transaction more than once in a row, you get the "This transaction has already been processed." error. In the case of Playground this is probably not the right behaviour, there are plenty of cases where you'd want to test the same instruction a few times in a row for example. An example where I've seen this is testing an instruction that reads from Pyth.

I'm guessing that the cause is the caching here: https://github.com/solana-playground/solana-playground/blob/master/client/src/utils/pg/tx.ts#L75 

I'm not sure what the right fix here is. Some ideas:

- update the blockhash without caching in the test UI because that's manual/user controlled and probably not responsible for most of the API requests
- a button in Settings to force fetching a new blockhash
-  detecting the error message and fetching the blockhash with some message so the user knows what's going on and the next attempt will work

**Comment by acheroncrypto** [comment]
Caching is very useful for the most part as it saves hundreds of API requests when deploying a program or deploying with `sugar-cli`. But the problem here is that when the instruction data and the latest blockhash of the transaction is the same, the transaction signature will be the same.

Another solution that came to my mind other than the ones you suggested is to catch for this exact error in `PgTx.send` and fetch the latest blockhash. This could be a better solution as everything will work as expected for the user and since every transaction in playground is sent via `PgTx.send`, no other changes would be needed.
