### ISSUE TITLE
Feature idea: Pyth price account address helper

### ISSUE THREAD

**Issue by mcintyre94** [solana-playground/solana-playground#117]
The test UI has really nice helpers for filling in addresses, and I think a Pyth one could be a good addition. Pyth requires passing in the address of a price account, and these are kinda fiddly to find. They're also network-dependent

I think we could have a Pyth option in the account dropdown (alongside eg Random, from seeds etc), and then present an autocomplete search where you can type eg "SOL/USD" and get the public key for SOL/USD on the currently selected network. I think this would make testing programs that use Pyth lots easier.

I'm not sure if there's an official version but we could use the seahorse CSV file for the data: https://github.com/ameliatastic/seahorse-lang/blob/main/data/pyth.csv

**Comment by acheroncrypto** [comment]
This sounds great but also a lot of potential unused data, so ideally we would want to lazy load the Pyth data only when it's necessary. I can work on this after #113.

**Comment by acheroncrypto** [comment]
Finally was able to add this in in https://github.com/solana-playground/solana-playground/commit/08db5a76ffcf9d5e711d7b7cc3e9f785b2eb615c

If you check the commit, you'll see how easy it was to add it but it's only because I've rewritten the whole test UI to make it extendible(took so much longer than I anticipated). There are still so many possible improvements but I think Pyth accounts helper is a great addition, thank you for the idea!

![test-ui-pyth](https://github.com/solana-playground/solana-playground/assets/98934430/2201a3be-2868-468b-b02c-cf9bc9edb8f2)
