### ISSUE TITLE
Example Program test doesn't work

### ISSUE THREAD

**Issue by chang47** [solana-playground/solana-playground#132]
At first I thought this was a problem with the program I wrote, but I realized that the example program doesn't work either.

Repro steps:
1. Visit: https://beta.solpg.io/
2. Create a new project 
3. Click Build
4. Click Test

Error message:
```
 Error: failed to send transaction: Transaction simulation failed: Attempt to debit an account but found no record of a prior credit.
```

**Comment by acheroncrypto** [comment]
Hey, you need SOL in your wallet in order to send transactions. If you are on devnet, you can use `solana airdrop 2` command. Playground used fund your wallet in devnet automatically prior to yesterday but because airdrop requests have been excessively rate-limited on devnet, you need to manually airdrop yourself for now.

If you have solana installed locally, you can start a test-validator with `solana-test-validator` and switch the network to `localhost` from the settings.

> Repro steps:
> 
> 1. Visit: https://beta.solpg.io/
> 2. Create a new project
> 3. Click Build
> 4. Click Test

If your tests includes your program(which most likely does), you'd need to deploy the program after the build step.

**Comment by chang47** [comment]
Thanks! That solved the problem! Thanks for your support! Closing the issue.
