### ISSUE TITLE
Request for dependencies used for Transfer Hook and Metadata Interface programs

### ISSUE THREAD

**Issue by ZYJLiu** [solana-playground/solana-playground#170]
Requesting the following dependencies so that examples can be run using Solana Playground

Rust Crates:
```
spl-token-metadata-interface = "0.2.0"
spl-type-length-value = "0.3.0"
spl-pod = "0.1.0"
spl-transfer-hook-interface = "0.4.1"
spl-tlv-account-resolution = "0.4.0"
```

TS library
- `@solana/spl-token-metadata`

Example usage:
- [Anchor Transfer Hook program](https://github.com/ZYJLiu/anchor-transfer-hook)
- [Anchor Metadata program](https://github.com/ZYJLiu/anchor-token-metadata)

**Comment by acheroncrypto** [comment]
Thanks, will add after https://github.com/solana-playground/solana-playground/issues/165 — sorry, this is taking a while.

**Comment by acheroncrypto** [comment]
Added all of them in https://github.com/solana-playground/solana-playground/commit/22d0028294b2e7ac68e126113d334369912616a4 but not some of them have different versions(compared to the ones you've given) due to `spl-token-2022` dependency not yet being on `1.0.0`. Can see the versions used in [supported-crates.json](https://github.com/solana-playground/solana-playground/blob/22d0028294b2e7ac68e126113d334369912616a4/supported-crates.json).

Again, sorry for the delay!
