### ISSUE TITLE
Unable to send and receive SOLs in playground's wallet

### ISSUE THREAD

**Issue by mshoaib112215** [solana-playground/solana-playground#193]
![image](https://github.com/solana-playground/solana-playground/assets/75632120/3e31e002-9392-4ff0-a536-864f323cc292)

A day before I can use this wallet for deployment and transfering SOLs accors devnet for testing purposes. But now it is not accepting and sending SOLs anywhere, as you can see in the image, I tried to send all SOLs to another account and it shows me success, but didn't send... Please assist me.

**Comment by acheroncrypto** [comment]
This is because devnet cluster is currently down unfortunately. It will most likely be up soon but in the meantime, you can use testnet or localnet(if you have `solana-test-validator` installed).

You can also check the ping status of the devnet RPC from https://explorer.solana.com/?cluster=devnet (at the bottom).

**Comment by acheroncrypto** [comment]
This should work now since devnet is back up.

I also realized the "Success." text in the terminal when devnet was down which shouldn't happen. Added a fix for it in https://github.com/solana-playground/solana-playground/commit/7b6cfa0ea8fa7f34a7c63ab763acb3ff4457122c by always confirming the transaction before printing success message.
