### ISSUE TITLE
[bug] "building..." hangs and does not show error in the console

### ISSUE THREAD

**Issue by brimigs** [solana-playground/solana-playground#205]
With the new anchor version, you now need to directly use `ctx.bump` instead of using `.get()`. If your program still uses the `.get()` method, an error is not generated when attempting to build your program on solana playground. Instead, "building..." just hangs in the console and will never generate the `method 'get' not found` error. 

Screenshot of building issue: 
<img width="686" alt="Screenshot of Firefox at Feb 27, 2024 at 12_15_28 PM" src="https://github.com/solana-playground/solana-playground/assets/85972460/95f0207a-466b-4380-a768-5d6f24c3d33f">

Successful build after removing this error from the code: 
<img width="736" alt="Screenshot of Firefox at Feb 27, 2024 at 12_16_09 PM" src="https://github.com/solana-playground/solana-playground/assets/85972460/44c020d8-5a58-4f01-a50a-a9bbda06e4d7">

**Comment by acheroncrypto** [comment]
It doesn't actually hang, the error message just gets filtered out. This was a false positive with detecting useless errors and was fixed in 6126b424ae6ccdbf6e870ae8db37d15cc01442c3 (but not yet deployed). I've just deployed it so it should work now.

There is a new "Improve build errors" setting to enable/disable this behavior (enabled by default).
