### ISSUE TITLE
Requesting for the use of latest crates namely anchor_spl 0.30.0 and others  

### ISSUE THREAD

**Issue by GunjanSurti** [solana-playground/solana-playground#228]
I'm using solpg for a while it the experience is great it pretty much does the heavy lifting.
I would loved see the integration of anchor_spl 0.30.0

Thank You for your hard work

**Comment by acheroncrypto** [comment]
This upgrade is more challenging than other upgrades mainly because of the Anchor IDL changes (which we also use in the app itself) and the new [`declare_program!`](https://github.com/coral-xyz/anchor/pull/2857) macro. Upgrading the crate versions won't be enough, and unfortunately, I don't know when I'll be able to get to this.

Thanks for your kind words!

**Comment by GunjanSurti** [comment]
Thank you for replying .

And we can use latest anchor version in vscode right?

**Comment by acheroncrypto** [comment]
Yes, of course.

https://www.anchor-lang.com/docs/installation
