### ISSUE TITLE
Deploying is stuck on devnet 

### ISSUE THREAD

**Issue by ytrobert** [solana-playground/solana-playground#229]
When deploying on devnet, the terminal says:"Deploying... This could take a while depending on the program size and network conditions.", and is stuck, even if it's a helloworld program.
Information:
1. F12, Console log: Buffer pk: ByqpbZVZmCZsU5WLCyTRE4NtiZcUKSaughJDfsQCAMnr
2. it seems there is no such issue on testnet

**Comment by acheroncrypto** [comment]
Unfortunately, it's because devnet is currently down.

Here are some links to track this issue:

https://explorer.solana.com/?cluster=devnet
https://twitter.com/SolanaDevnet/status/1781116618321608735
https://discord.com/channels/428295358100013066/749059399875690557/1230677600725368913

It would be nice to be able to display a notification of some sorts when the current cluster is down, but not sure what's the best way to decide if a cluster is down or not since it could just be an RPC that's down.

**Comment by ytrobert** [comment]
thanks a lot !!!
