### ISSUE TITLE
Add deploy button on main view

### ISSUE THREAD

**Issue by jacobcreech** [solana-playground/solana-playground#233]
During some user experience tests, users were having trouble figuring out how to deploy the program. They found the build button on the main screen, but expected the deploy program to also exist. Some users spent multiple minutes looking throughout the UI to find the deploy button.

**Suggestion**:

Add a deploy button next to the build button here:

<img width="438" alt="Screen Shot 2024-05-10 at 4 49 03 PM" src="https://github.com/solana-playground/solana-playground/assets/82475023/5b55e314-8c2f-4745-bb5d-aaf64be2999e">

Deploy button will automatically connect playground wallet if not connected already. IMO you don't have to go through the modal window for downloading a keypair, this is only for testing.

**Comment by acheroncrypto** [comment]
I was going to add this a long time ago, but there were some technical limitations due to the deployment button making some checks that require RPC request, like the program authority check. We have a separate implementation of the deployment logic as a command now (https://github.com/solana-playground/solana-playground/commit/6b611bae541f52964fac90fa676c404822d4dca1), so we should be able to add this that way.

> IMO you don't have to go through the modal window for downloading a keypair, this is only for testing.

Even devnet funds can be valuable sometimes, and there are actually a lot of people who use the playground for doing mainnet deployments due to `solana-cli` issues.

**Comment by jacobcreech** [comment]
> Even devnet funds can be valuable sometimes, and there are actually a lot of people who use the playground for doing mainnet deployments due to solana-cli issues.

Agreed on that. Maybe it's a different ux flow for the keypair creation then. The users were unsure what happened after creating a keypair, and took a while to find the deploy button when they have to create it first.

> use the playground for doing mainnet deployments due to solana-cli issues.

Is there a way to pull this out standalone cli for people to use? It is further ahead than the Solana cli today

**Comment by acheroncrypto** [comment]
> Maybe it's a different ux flow for the keypair creation then. The users were unsure what happened after creating a keypair, and took a while to find the deploy button when they have to create it first.

We can do something like the following:

1. Add Deploy button next to Build in the explorer page
2. Only the first time ever, clicking Deploy shows the wallet modal
3. Accepting the modal starts the deployment immediately

> Is there a way to pull this out standalone cli for people to use? It is further ahead than the Solana cli today

Of course, but I'm unsure if it's worth it anymore since the `solana-cli` has been getting many fixes recently. I would have updated [`solana-deployer`](https://github.com/acheroncrypto/solana-deployer) long ago if I knew it was going to take this long though.

**Comment by acheroncrypto** [comment]
Added all the things I mentioned in [the above post](https://github.com/solana-playground/solana-playground/issues/233#issuecomment-2105546040).

![Deploy button](https://github.com/user-attachments/assets/cfac74b7-3b25-447d-92af-2f44841c742c)

It also:

- Connects if the wallet is not connected
- Builds the program if the program is not built

![Connect, build and deploy](https://github.com/user-attachments/assets/62fb3a36-b869-4e9e-9125-cc4ca0d934b0)
