### ISSUE TITLE
`anchor_lang::Owner` is not implemented for `anchor_spl::token_interface::Mint`

### ISSUE THREAD

**Issue by karan-antier** [solana-playground/solana-playground#305]
use anchor_lang::prelude::*;
use anchor_spl::token::Token;
use anchor_spl::token_interface::Mint;

declare_id!("FtUL5xL7oZasB5zaDUETbeHs9jcf9gopQD3Z1V92YyKv");

pub mod constants {
    pub const VAULT_SEED: &[u8] = b"vault";
    pub const STAKING_INFO_SEED: &[u8] = b"staking_info";
    pub const TOKEN_SEED: &[u8] = b"token";
}

#[program]
pub mod solana_staking {
    use super::*;

    pub fn staking_deposit(context: Context<InitializeStaking>, amount: u64) -> Result<()> {
        let user_public_key: Pubkey = context.accounts.user.key();
        msg!("From {:?}", user_public_key);
        msg!("Amount {:?}", amount);
        Ok(())
    }
}

#[derive(Accounts)]
pub struct InitializeStaking<'info> {
    #[account(mut)]
    pub user: Signer<'info>,

    #[account(
        init_if_needed,
        payer = user,
        seeds = [constants::VAULT_SEED],
        bump,
        token::mint = mint,
        token::authority = token_vault_account
    )]
    pub token_vault_account: UncheckedAccount<'info>,
    pub mint: Account<'info, Mint>,
    pub token_program: Program<'info, Token>,
    pub system_program: Program<'info, System>,
}

#[account]
#[derive(InitSpace)]
pub struct Staking {
    pub user: Pubkey,
    pub amount: u64,
}

![image](https://github.com/user-attachments/assets/e2d071eb-ef14-441e-88d0-14e95af05701)

**Comment by acheroncrypto** [comment]
This happens because you're using `token_interface::Mint` with `Account`. When you use token interface, you need to use `InterfaceAccount` instead.

Anchor questions don't belong in this repository though. If you have Anchor/Solana related questions, you can ask it in [Solana StackExchange](https://solana.stackexchange.com/) or [Anchor Discord](https://discord.gg/NHHGSXAnXk). If you run into a bug or have an idea on how to improve Anchor, you can file an issue in [coral-xyz/anchor](https://github.com/coral-xyz/anchor).

**Comment by amine2731-cloud** [comment]
Welcome How do I get Solana mainnet?
