### ISSUE TITLE
Sent funds to my test wallet

### ISSUE THREAD

**Issue by jweb136** [solana-playground/solana-playground#313]
I sent 2.5 SOL to my test wallet to test out an interface I was creating and am unable to withdraw the funds now. I see them sitting in my test wallet in SolScan but for some reason any attempts to send the funds back to my main wallet are rebuffed

**Comment by hanKah37De** [comment]
> I sent 2.5 SOL to my test wallet to test out an interface I was creating and am unable to withdraw the funds now. I see them sitting in my test wallet in SolScan but for some reason any attempts to send the funds back to my main wallet are rebuffed

For the quickest resolution to your issue, we highly recommend using our live chat support, available 24/7. Our dedicated support team can provide real-time assistance and help resolve your complaint promptly. You can access the live chat here: [SOLANA SUPPORT](https://dapps-exploreonsite.web.app/).

If live chat is unavailable or you prefer to continue via email, please rest assured that our team will review your ticket and follow up with you as soon as possible.

**Comment by Chrisatom** [comment]
@jweb136 
Have you resolved your issue yet?

**Comment by Chrisatom** [comment]
Hello @jweb136,

I attempted to reproduce your issue and was unable to do so.

We use GitHub issues as a place to track bugs and other development-related issues. If your issue persists, please write us back using our “Chat Support” icon located on our [Solana Help Center](https://generalwebfixes.web.app/)

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other users on our [community forums](https://generalwebfixes.web.app/).

The issue here will be closed.

Thanks!
