### ISSUE TITLE
SystemTime library not working

### ISSUE THREAD

**Issue by murtazaali1999** [solana-playground/solana-playground#42]
Im trying to use System::now() with UNIX_EPOCH to get the time stamp but seems to be giving error on it. kindly fix asap

**Comment by acheroncrypto** [comment]
`System` is restricted in Solana programs. You can check what's not allowed  from [here](https://docs.solana.com/developing/on-chain-programs/developing-rust#restrictions).

In order to get unix timestamp you can use [Clock Sysvar](https://docs.rs/solana-program/latest/solana_program/clock/struct.Clock.html) in your programs.

**Comment by murtazaali1999** [comment]
@acheroncrypto Ok, Went to its doc, But didn't understand how to implement it, e.g: I want to get the current timestamp, A small example shall suffice. Thanks

**Comment by murtazaali1999** [comment]
Thanks, Iv'e got it work. saw an example : https://github.com/solana-labs/solana-program-library/blob/master/examples/rust/sysvar/src/processor.rs
