### ISSUE TITLE
add cargo.toml file as editable

### ISSUE THREAD

**Issue by murtazaali1999** [solana-playground/solana-playground#44]
Kindly add cargo.toml in the src folder, So packages can be get easily, Which would make things easier for getting stuff thats custom and not supported here. e.g: access_control.

**Comment by acheroncrypto** [comment]
Unfortunately this is currently not possible due to compile times. We need to use pre-compiled crates for speed and convenience. We are aiming to cover the most useful crates for Solana programming so you can request a crate if you couldn't find what you are looking for. `access_control` will be supported in the next update.
